tasks:
  - name: Setup Database
    init: docker compose pull
    command: |
      docker compose up -d
      exit
  - name: Setup Python
    init: |
      python -m venv /workspace/.python-venv/python
      source /workspace/.python-venv/python/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    command: |
      echo "source /workspace/.python-venv/python/bin/activate" >> ~/.bashrc
      exit
vscode:
  extensions:
    - ms-python.python
    - formulahendry.code-runner
    - ms-toolsai.jupyter-keymap
    