# Generated by Django 4.0.4 on 2022-04-21 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clones', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
