# Generated by Django 4.0.4 on 2022-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clones', '0005_alter_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
