# Generated by Django 4.0.4 on 2022-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clones', '0006_alter_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('1', 'Ongoing'), ('2', 'Past Event'), ('3', 'Event Cancelled')], default='1', max_length=3),
        ),
    ]
