# Generated by Django 4.0.4 on 2022-04-30 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clones', '0010_alter_event_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
